#dnf module disable nodejs -y
#dnf module enable nodejs:20 -y
#
#dnf install nodejs -y
#
#cp cart.service /etc/systemd/system/cart.service
#
#useradd roboshop
#
#mkdir /app
#cd /app
#
#curl -L -o /tmp/cart.zip https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
#unzip /tmp/cart.zip
#
#npm install
#systemctl daemon-reload
#
#systemctl enable cart
#systemctl start cart

---
- name: Cart Setup
  hosts: all
  become: true
  tasks:
    - name: Installing Node js
      ansible.builtin.dnf:
        name: '@nodejs:20'
        state: present

    - name: Copying cart service file
      ansible.builtin.copy:
        src: cart.service
        dest: /etc/systemd/system/cart.service

    - name: Creating user
      ansible.builtin.user:
        name: roboshop

    - name: Creating app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download and extract app content
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
        dest: /app
        remote_src: yes

    - name: Installing required packages
      community.general.npm:
        path: /app

    - name: Restart the service
      ansible.builtin.service:
        name: cart
        state: restarted
        enabled: true
        daemon_reload: true