#dnf install mysql-server -y
#
#systemctl enable mysqld
#systemctl restart mysqld
#
#mysql_secure_installation --set-root-pass RoboShop@1

---

- name: MySql Setup
  hosts: all
  become: true
  tasks:
    - name: Installing mysql server
      ansible.builtin.dnf:
        name: mysql-server
        state: present

    - name: Restart the mysql service
      ansible.builtin.service:
        name: mysqld
        state: restarted
        enabled: true

    - name: SetUp Mysql password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1

