#dnf module disable redis -y
#dnf module enable redis:7 -y
#
#dnf install redis -y
#
#sed -i -e 's/127\.0\.0\.1/0.0.0.0/' -e 's/^protected-mode yes/protected-mode no/' /etc/redis/redis.conf
#
#systemctl enable redis
#systemctl restart redis

---
- name: Setup redis
  hosts: all
  become: true
  tasks:
    - name: Installing redis
      ansible.builtin.dnf:
        name: '@redis:7'
        state: present

    - name: Replacing IP address
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Replacing Protected Mode
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: 'protected-mode yes'
        replace: 'protected-mode no'

    - name: Start redis server
      ansible.builtin.service:
        name: redis
        state: restarted
        enabled: true

