#dnf install maven -y
#
#
#cp shipping.service /etc/systemd/system/shipping.service
#
#useradd roboshop
#
#mkdir /app
#
#curl -L -o /tmp/shipping.zip https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
#  # shellcheck disable=SC2164
#cd /app
#unzip /tmp/shipping.zip
#
#  # shellcheck disable=SC2164
#cd /app
#mvn clean package
#mv target/shipping-1.0.jar shipping.jar
#
#dnf install mysql -y
#
#mysql -h 100.27.250.232 -uroot -pRoboShop@1 < /app/db/schema.sql
#mysql -h 100.27.250.232 -uroot -pRoboShop@1 < /app/db/app-user.sql
#mysql -h 100.27.250.232 -uroot -pRoboShop@1 < /app/db/master-data.sql
#
#systemctl daemon-reload
#systemctl enable shipping
#systemctl restart shipping

---

- name: Shipping Setup
  hosts: all
  become: true
  tasks:
    - name: Install Maven
      ansible.builtin.dnf:
        name: 'maven'
        state: present

    - name: Add roboshop application user
      ansible.builtin.user:
        name: roboshop

    - name: Remove app directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download and extract app content
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
        dest: /app
        remote_src: yes

    - name: Install maven dependencies
      ansible.builtin.shell: mvn clean package ; mv target/shipping-1.0.jar shipping.jar
      args:
        chdir: /app/

    - name: Install MySQL Client
      ansible.builtin.dnf:
        name: mysql
        state: present

    - name: Load schema
      ansible.builtin.shell: mysql -h mysql-dev.chanakyakolli.online -uroot -pRoboShop@1 < /app/db/schema.sql

    - name: Load user
      ansible.builtin.shell: mysql -h mysql-dev.chanakyakolli.online -uroot -pRoboShop@1 < /app/db/app-user.sql

    - name: Load master data
      ansible.builtin.shell: mysql -h mysql-dev.chanakyakolli.online -uroot -pRoboShop@1 < /app/db/master-data.sql

    - name: Copy shipping service file
      ansible.builtin.copy:
        src: shipping.service
        dest: /etc/systemd/system/shipping.service

    - name: Start Shipping service
      ansible.builtin.service:
        state: restarted
        name: shipping
        enabled: true
        daemon_reload: true