#dnf module disable nodejs -y
#dnf module enable nodejs:20 -y
#
#dnf install nodejs -y
#
#cp user.service /etc/systemd/system/user.service
#useradd roboshop
#
#mkdir /app
#  # shellcheck disable=SC2164
#cd /app
#
#curl -L -o /tmp/user.zip https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
#unzip /tmp/user.zip
#
#npm install
#
#systemctl daemon-reload
#
#systemctl enable user
#systemctl restart user

---
- name: User Setup
  hosts: all
  become: true
  tasks:
    - name: Installing Node js
      ansible.builtin.dnf:
        name: '@nodejs:20'
        state: present

    - name: Copying user service file
      ansible.builtin.copy:
        src: user.service
        dest: /etc/systemd/system/user.service

    - name: Creating user
      ansible.builtin.user:
        name: roboshop

    - name: Creating app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download and extract app content
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
        dest: /app
        remote_src: yes

    - name: Installing required packages
      community.general.npm:
        path: /app

    - name: Restart the service
      ansible.builtin.service:
        name: user
        state: restarted
        enabled: true
        daemon_reload: true





